"""empty message

Revision ID: 00daff3ffd6d
Revises: 1601a5deebf0
Create Date: 2025-12-16 18:15:14.803026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00daff3ffd6d'
down_revision = '1601a5deebf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
