"""add phone number to user

Revision ID: 031028060814
Revises: 1f61a3c8f45e
Create Date: 2026-01-24 08:59:01.783151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '031028060814'
down_revision = '1f61a3c8f45e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
