"""empty message

Revision ID: 18304085cfc5
Revises: 338bf480cc92
Create Date: 2025-12-16 14:49:14.875448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18304085cfc5'
down_revision = '338bf480cc92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
