"""empty message

Revision ID: 338bf480cc92
Revises: 157ace8c56f4
Create Date: 2025-12-16 10:25:31.347906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338bf480cc92'
down_revision = '157ace8c56f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
