"""empty message

Revision ID: 3d70fde9e6c1
Revises: 00daff3ffd6d
Create Date: 2025-12-17 20:47:12.523103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d70fde9e6c1'
down_revision = '00daff3ffd6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.drop_column('is_thumbnail')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_thumbnail', sa.VARCHAR(length=5), nullable=False))

    # ### end Alembic commands ###
