"""update_user_add_email

Revision ID: 54ce20f944d6
Revises: 3d70fde9e6c1
Create Date: 2026-01-23 15:42:45.909680

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '54ce20f944d6'
down_revision = '3d70fde9e6c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint('uq_user_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
