"""empty message

Revision ID: 95b052cd977e
Revises: 2b7bdfba1c4d
Create Date: 2025-12-15 11:29:10.401852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95b052cd977e'
down_revision = '2b7bdfba1c4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=1),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=1),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    # ### end Alembic commands ###
